xoofx/CppAst.NET

src/CppAst.Tests/TestFunctions.cs
src/CppAst/CppModelBuilder.cs

Hi, thanks for this library - I'm making good use of it to generate a pinvoke wrapper using Roslyn AST to generate the code. It's working well apart from this bug I hit with a struct that contains function pointer fields, the CppAst result duplicated the first function pointer field's parmaters to all the rest. See the test for an example.
The fix makes sense to me, and passes current test suite but I might be going the wrong way with it. I've not used libclang before.

Fix function pointer fields share parameters

---

src/CppAst/CppModelBuilder.cs
src/CppAst/CppParser.cs
src/CppAst/CppParserOptions.cs

Right now if you have a larger project that includes many 3rd party headers or pulls in a lot of system headers, this can increase the parse time a huge amount especially if you don't care about the results of that content. 
This adds an option that allows you to skip the parsing of SystemIncludes, which in my case resulted with my parse going from 38s to 1s (since a large chunk of the code pulls in 3rd party libs). 
I do understand if this is not something you want to support but I thought I would make the PR anyway. :D

Adding support for skipping the parsing of SystemInclude Headers

---

src/CppAst.Tests/TestTypeAliases.cs
src/CppAst/CppModelBuilder.cs

Allow for the parsing of TypeAliases as Typedefs, added tests for template and non-template case.

Allow for the parsing of TypeAliases

---

src/CppAst.Tests/TestAttributes.cs
src/CppAst.Tests/TestFunctions.cs
src/CppAst/CppClass.cs
src/CppAst/CppContainerList.cs
src/CppAst/CppEnum.cs
src/CppAst/CppFunction.cs
src/CppAst/CppGlobalDeclarationContainer.cs
src/CppAst/CppModelBuilder.cs
src/CppAst/CppNamespace.cs
src/CppAst/ICppDeclarationContainer.cs

This PR is a little complicated when C++11 added support for a standard around attributes, it had some rules around what was valid and what wasn't valid. In many cases, libClang doesn't give us all the information we need to be able to parse these attributes, and this became even more so of a thing when C++17 allowed for essentially user-defined attributes because the compiler would no longer complain about an attribute it didn't know about it just ignores it.
In this PR we when we parse attributes we need to take some manual steps to resolve cases where we are using C++11 style attributes and libClang doesn't return to the developer the actual proper CXSourceRanges that include these attributes. This why the AttributeTokenizer has been introduced and essentially creates its own range …

Better Attribute parsing support

---

src/CppAst.Tests/TestAttributes.cs
src/CppAst.Tests/TestComments.cs
src/CppAst/CppModelBuilder.cs

Fixing issues where if you had a ) in a comment it would cause an infinite loop mentioned in issue #17 
I also added support for properly parsing "alignas" attribute

Fixing infinite loop issue caused by attribute parsing. 

---

src/CppAst.Tests/TestAttributes.cs
src/CppAst/CppModelBuilder.cs

So this is a case where if you have an attribute on a variable that has an inlined type such as a `std::vector<int>` libClang doesn't treat this the same way as a standard variable so its require that we parse it slightly differently which we were doing but we were not including the result of that in the final range that gets returned back to `AttributeTokenParser`.
We now do this where if we have a secondary range which happens in this case, we then include that range in the final range that gets sent back. 
I have added two tests, one that covers this case and another that verifies other template cases.

Attributes on Vars with in-lined types. 

---

src/CppAst.Tests/TestAttributes.cs
src/CppAst.Tests/TestComments.cs
src/CppAst.Tests/TestFunctions.cs
src/CppAst/CppModelBuilder.cs
src/CppAst/CppParser.cs
src/CppAst/CppParserOptions.cs

This PR adds the `ParseAttributes` option to skip parsing attributes.
`ParseFunctionAttributes` and `ParseAttributes` function takes a long time to complete, so I propose to add an option to skip these functions.

add ParseAttributes option

---

src/CppAst/CppModelBuilder.cs

In the previous implementation, the function `GetNextLocation` is very slow because of its relying on `tu.GetLocationForOffset` which has to do some extra scanning over the entire TranslationUnit. 
Calling this function is actually not required in most cases, because when scanning for attributes there is a common pattern where the attribute is on the same line, so we really can deal with things on a line/column basis instead of a offset into the entire translation unit. LibClang has a function that allows you to get the location based on passing in a line and column instead of an offset. This function is significantly faster. 
When using the test code from #20: 
```
var sw = new System.Diagnostics.Stopwatch();
sw.Start();
for (var i = 0; i < 10; ++i)
{
var options = new …
```

Optimize Attribute Parsing

---

src/CppAst.Tests/TestTypes.cs
src/CppAst/CppClass.cs
src/CppAst/CppFunction.cs
src/CppAst/CppModelBuilder.cs
src/CppAst/CppUnexposedType.cs
src/CppAst/ICppTemplateOwner.cs

This PR adds TemplateParameter parsing to `CppClass` and `CppUnexposedType`.
Template parameters must be parsed recursively, so I changed TemplateParameters type to `List<CppType>`.
```cs
// ICppTemplateOwner
// before
List<CppTemplateParameterType> TemplateParameters { get; }
// after
List<CppType> TemplateParameters { get; }
```

add support for TemplateParameter parsing

---

src/CppAst.Tests/TestTypes.cs
src/CppAst/CppClass.cs
src/CppAst/CppModelBuilder.cs

This PR adds to retrieve which templates are specialized.
```
template <typename T>
class Foo {};
Foo<int> int_foo;
```
You can parse `Foo<int>` to get an `int` as a template parameter and `Foo<T>` as a specialization class template.

Add support for specialized template

---

src/CppAst.Tests/TestTypes.cs
src/CppAst/CppModelBuilder.cs

This PR fixes an issue where parsing a prototype-declared class would result in duplicate qualifiers being added.
```cpp
namespace ns1 {
class TmpClass;
}
namespace ns2 {
const ns1::TmpClass* tmpClass1;    // Type is const const TmpClass*
volatile ns1::TmpClass* tmpClass2;  // Type is volatile volatile TmpClass*
}
```

fix parsing qualifier

---

src/CppAst.Tests/TestAttributes.cs
src/CppAst.Tests/TestTypeAliases.cs
src/CppAst.Tests/TestTypes.cs
src/CppAst/CppClass.cs
src/CppAst/CppModelBuilder.cs

This PR improves two template parsing.
1. Fixes a bug where the same `HashCode` is returned even if `TemplateParameters` is different.
1. Parse the `Declaration` even when the type is `CXType_Unexposed`.

Improve parsing template

---

src/CppAst.Tests/TestNamespaces.cs
src/CppAst/CppModelBuilder.cs

Hi there,
This PR fixes https://github.com/xoofx/CppAst.NET/issues/48
i found the reason for the failed typedef resolution:
When a reference to a typedef in a different namespace gets parsed, it won’t be of thy type `CXType_Typedef` but `CXType_Elaborated`.
The solution was to try to find an already defined typedefs when encountering a `CXType_Elaborated` before creating a new Type.
I also created a test-case for this bug.

Fix for typedef in different namespace

---

src/CppAst.Tests/TestFunctions.cs
src/CppAst/CppFunction.cs
src/CppAst/CppFunctionFlags.cs
src/CppAst/CppModelBuilder.cs

This should fix #40. Just adding a simple function flag indicating that a function has variadic arguments and code/tests to support it.
I considered also adding support to function types (same basic code), but I was unsure about how it should be implemented. I could have either added a boolean property `IsVariadic` or I could have added a `Flags` property similar to the way it is done on `CppFunction`.

Add support for variadic function arguments.

---

src/CppAst.Tests/TestStructs.cs
src/CppAst/CppField.cs
src/CppAst/CppModelBuilder.cs

It would be nice to have offset exposed. Specifically, I'd like to use it for ExplicitLayout when generating C# bindings.

Add Offset to CppField

---

src/CppAst.Tests/TestFunctions.cs
src/CppAst.Tests/TestNamespaces.cs
src/CppAst/CppBaseType.cs
src/CppAst/CppClass.cs
src/CppAst/CppElement.cs
src/CppAst/CppEnum.cs
src/CppAst/CppFunction.cs
src/CppAst/CppFunctionFlags.cs
src/CppAst/CppGlobalDeclarationContainer.cs
src/CppAst/CppModelBuilder.cs
src/CppAst/CppNamespace.cs
src/CppAst/CppTemplateArgument.cs
src/CppAst/CppType.cs
src/CppAst/CppTypeKind.cs
src/CppAst/CppTypedef.cs

1. add support for function template
2. add inline namespace support
3. change FullName as a CppType property, and deduce the CppClass full name with specialized template right, you can just use CppClass full name in a generated c++ codes now.
4. FindByFullName() now can search auto ignore inline namespace now(such as clang std::__1::vector, now you can just use std::vector to search)
5. fix crash when the CppClass has a  specialized template with PartialSpecializedTemplateDecl
6. fix crash when typedef with a AliasTemplateDecl for Underlying type.

Enhance for function template & CppType FullName support.

---

src/CppAst.Tests/InlineTestBase.cs
src/CppAst.Tests/TestTypeAliases.cs
src/CppAst.Tests/TestTypedefs.cs
src/CppAst/CppAst.csproj
src/CppAst/CppModelBuilder.cs

Update ClangSharp to 16.0.0, some tests failes due to how squash types are handled. any thoughts?

Update ClangSharp to 16.0.0

---

src/CppAst.Tests/AttributesTest/TestTokenAttributes.cs
src/CppAst/CppModelBuilder.cs
src/CppAst/CppTokenUtil.cs

Adding support for parsing attributes defined as a macro, and parsing function attributes that are on a separate line before the function declaration.

Improve attribute parsing

---

src/CppAst.Tests/TestTypes.cs
src/CppAst/CppPointerType.cs
src/CppAst/CppQualifiedType.cs

Move the qualifier to the end of it's ToString Method.
To increase the readability due to this change also a space is inserted between the ElementType's Name and the Pointer-Character (*) in the CppPointerType.
This will solve the problem mentioned in #70 .
Examples for the Input and Output **before** the change:
const int * const   => const const int* (syntactically incorrect)
int const * const   => const const int* (syntactically incorrect)
const int *            => const int*           (syntactically correct)
const int              => const int             (syntactically correct)
Examples for the Input and Output **after** the change:
const int * const   => int const * const (syntactically correct)
int const * const   => int const * const (syntactically correct)
const int * …

Move Qualifier at the end in CppQualifiedType

---

src/CppAst/CXUtil.cs
src/CppAst/CppModelBuilder.cs
src/CppAst/CppParser.cs
src/CppAst/CppTokenUtil.cs

Memory leak fix

---

src/CppAst/CppPrimitiveType.cs

type "long" and "unsigned long" are missed in ToString()

fix "Unhandled PrimitiveKind: Long" in CppPrimitiveType.ToString()

---

src/CppAst.Tests/TestTypeAliases.cs
src/CppAst.Tests/TestTypedefs.cs
src/CppAst/CppPrimitiveType.cs

This pull request replaces occurrences of `wchar` with `wchar_t` to ensure code standardization and improve compatibility across platforms.
- **Issue**: `wchar` is not a standard keyword and may cause compatibility issues.
- **Fix**: Replaced `wchar` with the standardized `wchar_t`.
For more details on `wchar_t`, see the [cppreference documentation](https://en.cppreference.com/w/cpp/keyword/wchar_t).

Fix: Replace wchar with wchar_t for standardization and compatibility
